### ISSUE TITLE
makel: testing byte-compiled files?

### ISSUE THREAD

**Issue by alphapapa** [DamienCassou/emacs.d#4]
Hi Damien,

Forgive me for contacting you this way, but the registration page on `makel`'s site says:

> User registration is now closed due to spam. Please contact Nico to create an account.

Perhaps you would consider moving or mirroring the repo here so issues could be filed on it?  :)

Anyway, I started using `makel` for https://github.com/alphapapa/ts.el, and I like it very much!

However, I've noticed that, by setting `load-prefer-newer`, it doesn't test byte-compiled versions of files if they haven't been compiled since being modified.  Most of the time this doesn't matter, but in one of my other packages I found a difference in behavior when byte-compiled.  It was minor, and I eventually resolved it with a simple change to the code, however it showed that it is good to test code in its byte-compiled form, since that's what most users will end up running.

So this means that my workflow should be something like:

1.  Make changes to code.
2.  Save `.el` file.
3.  Byte-compile the file from within Emacs.
4.  Run tests with `makel`.

If I forget step 3 (which I often do), the tests will run, but they will test the interpreted code rather than the byte-compiled code.  And since `makel`'s purpose is to make development easier and more reliable, it seems like it should handle step 3 for me.  :)

What do you think?  Could `makel` byte-compile the files before running tests?

I tried doing this myself by adding this to my Makefile:

```mk
.PHONY: test-compiled

test-compiled: lint-compile test-ert
```

Then I run `make test-compiled`, and it works, but it also lints, which I don't always want (e.g. I currently have the `test.el` file being byte-compiled, which works but raises a warning, which clutters the output).

It also seems like the `test` rule should test byte-compiled files by default, which I guess would require `makel` itself to be changed, so I wouldn't have to override the rule in my Makefile.

Thanks for your work!

**Comment by alphapapa** [comment]
@DamienCassou It occurred to me that you probably don't expect to see issues filed here, so you probably wouldn't notice this unless I tag you in a comment.  :)

**Comment by DamienCassou** [comment]
I'm on vacation so I spend less time in front of a computer. I'm ok modifying makel to test byte-compiled files provided they are up-to-date. Do you mind trying?

**Comment by DamienCassou** [comment]
@NicolasPetton:  it would be great if anyone could create an account on your gitlab.

**Comment by NicolasPetton** [comment]
@DamienCassou It was the case, but I had to (temporarily) disable it due to a crazy amount of spam. I'll try and fix the issue when I'll be back from vacations.

**Comment by alphapapa** [comment]
@DamienCassou Well, I started working on making the changes, but I ran out of patience with the Makefile language.  :)  So I threw this together: https://github.com/alphapapa/makem.sh/blob/master/makem.sh  It doesn't support parallel execution of rules, but I can live with that.

Since I guess I don't need this feature in makel anymore, I'll close this issue.  Thanks for your help.
