### ISSUE TITLE
[Question] Emacs pass related packages

### ISSUE THREAD

**Issue by doolio** [DamienCassou/emacs.d#5]
I hope it is okay to reach out to you this way rather than via email. 

I notice from your `init.el` you use the following packages:

- [auth-source-pass](https://github.com/DamienCassou/auth-password-store) (which you also developed)
- [pass](https://github.com/NicolasPetton/pass) (which you have developed with Nicholas)
- [password-store](https://git.zx2c4.com/password-store/tree/contrib/emacs/password-store.el)

And I see you have also contributed to [password-store-otp](https://github.com/volrath/password-store-otp.el) though I could see no reference to it in your `init.el`. I'm in the process of changing all my passwords and the management of them and was curious if it was necessary to utilise all these packages to use [pass](https://www.passwordstore.org/) from within Emacs.

I presume each package provides functionality not provided by the others. Is this the case?

With respect to your `auth-source-pass` I understand it is now included with Emacs. I'm currently using 26.3  so can I assume it has the latest version bundled with it?

Thanks for your time.

**Comment by DamienCassou** [comment]
Hi 

doolio <notifications@github.com> writes:

> I hope it is okay to reach out to you this way rather than via email. 

sure. I prefer email but I can adapt (anyway, I'm answering from Emacs
in my email client). 

> you have also contributed to password-store-otp though I could see no
> reference to it in your `init.el`.

password-store-otp is a dependency of pass.el, the major-mode.

> I'm in the process of changing all my passwords and the management of
> them

you won't regret it. All my passwords are now stored there and all
applications read the store.

> and was curious if it was necessary to utilise all these packages to
> use pass. I presume each package provides functionality not provided
> by the others. Is this the case?

indeed.

- auth-source-pass: makes Emacs capable of reading your password store
  when it needs a password. This happens for example if you use magit
  with the https protocol, if you send emails from Emacs, if you use
  tramp, … You may only install this one when you start getting password
  requests from Emacs.

- pass: it is a kind of dired-mode dedicated to password-store. It makes
  your life simpler but is not mandatory.

- password-store: this is the official library providing the functions
  that pass needs.

> With respect to your `auth-source-pass` I understand it is now
> included with Emacs. I'm currently using 26.3 so can I assume it has
> the latest version bundled with it?

it is included. The version on melpa has some improvements over the
version in Emacs 26.3. I suggest you use the version provided with Emacs
until you miss some feature that is implemented in a more recent
version.

Feel free to contact me again.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by doolio** [comment]
Thank you for taking the time to provide such detail. This is very useful.
